title: Arbitration Guide
description: Arbitration Guide Description
theme: just-the-docs

url: https://xoxfaby.github.io/Arbitration-Guide/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
