title: Arbitration Guide
description: Arbitration Guide Description
theme: just-the-docs
color_scheme: dark

url: https://guide.faby.dev/Arbitration-Guide

aux_links:
  Arbitration Discord: https://discord.gg/7FTA7sQ

collections:
  guides:
    output: true
  - builds

just_the_docs:
  collections:
    guides:
      name: Guides
